### ISSUE TITLE
친애하는 나의 동지 현경동무에게

### ISSUE THREAD

**Issue by HoonBear** [petiechoi/community_python#1]
동무, 우리 조국에서 지령이 내려왔어

친애하는 현경동무의 살발한 와꾸로다가 남조선인민아세끼들을 접수하라는 명령이오.

부디 건투를 비오.

**Comment by petiechoi** [comment]
저와는 무관한 이슈입니다.
저는 평화를 좋아합니다.

**Comment by HoonBear** [comment]
> 저와는 무관한 이슈입니다. 저는 평화를 좋아합니다.

구라 ㄴ
